** Разложение функции в ряд Тейлора (Маклорена)

Из материалов лекции по дисциплине Математика от 21.10.2020:

Пусть функция \(y = f(x)\) определена в некоторой точке \(x = a\) и в
окрестности этой точки и имеет производные до \(n + 1\) порядка. Тогда
существует точка c, лежащая между точками x и a такая, что выполняется
формула Тейлора:

\[f(x) = f(x) + f'(a) (x - a) + f''(a)\frac{(x - a)^2}{2!} +
f'''(a)\frac{(x - a)^3}{3!} + ... + f^{(n)}(a)\frac{(x - a)^n}{n!} +
f^{(n + 1)}(c)\frac{(x - 1)^{n + 1}}{(n + 1)!}\]

Последнее слагаемое - остаточный член в форме Лангранжа:

\[R_{n + 1}(x) = f^{(n + 1)}(c)\frac{(x - a)^{n + 1}}{(n + 1)!}\]

Формулу Тейлора при \(a = 0\) называют формулой Маклорена. Она имеет
вид:

\[f(x) = f(0) + f'(0) x +
f''(0)\frac{x^2}{2!} +
f'''(0)\frac{x^3}{3!} + ... +
f^{(n)}(0)\frac{x^n}{n!} +
f^{(n + 1)}(\theta x)\frac{x^{n + 1}}{(n + 1)!},
0 < \theta < 1\]

** Вычисление значения разложенных функций

Из материалов лекции:

Т.к. факториал - это очень быстро растущая функция (50! не умещается в
разрядную сетку типа float), следует упростить вычисление n-ого члена
разложения.

Для нахождения члена q_n ряда Тейлора можно применить формулу:

\[c = \frac{q_n}{q_{n - 1}}\]

\[q_n = q_{n - 1} \cdot c\]

Нахождение каждого последующего члена происходит путём домножения
предыдущего на c. Это позволяет избавиться от факториала.
